### ISSUE TITLE
AttributeError: 'odict_values' object has no attribute 'reverse'

### ISSUE THREAD

**Issue by danie1k** [coderfly/fixtures-mongoengine#6]
Python version: 3.5.2

Error appears in two lines:
1. https://github.com/coderfly/fixtures-mongoengine/blob/master/fixtures_mongoengine/mixin.py#L161
2. https://github.com/coderfly/fixtures-mongoengine/blob/master/fixtures_mongoengine/mixin.py#L171

```python
    ...

    fixtures = self.get_fixtures().values()
    fixtures.reverse()

    ...
```

**Reason:**
- `self.get_fixtures()` returns an `OrderedDict` object,
- `self.get_fixtures().values()` returns an `odict_values` object,

But, at least in Python 3.5.2 it's not possible to call `reverse()` on `odict_values`.

**Easiest workaround:**
```python
fixtures = list(self.get_fixtures().values())
```

I haven't investigated it deeper.

**Comment by gruia-dev** [comment]
@danie1k the same problem, thank you for solution, made pull request

**Comment by coderfly** [comment]
Thanks for fix
